name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        working-directory: InfoSec
        run: mvn clean install

      - name: Run SpotBugs
        run: mvn spotbugs:check

      - name: Generate SpotBugs report
        run: mvn spotbugs:spotbugs

      - name: List SpotBugs output
        run: ls target/spotbugs


      - name: Upload SpotBugs report
        uses: actions/upload-artifact@v2
        with:
         name: spotbugs-report
         path: target/spotbugs/spotbugsXml.xml
      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk test
        run: snyk test --all-projects --json > snyk-report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}



