name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Укажите нужную версию JDK
          distribution: 'temurin'

      - name: Build with Maven
        working-directory: ./InformationSecurity_Lab1/InfoSec
        run: mvn clean install

      - name: Run SpotBugs
        working-directory: ./InformationSecurity_Lab1/InfoSec
        run: mvn spotbugs:check