name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        working-directory: InfoSec
        run: mvn clean install

      - name: Run SpotBugs
        working-directory: InfoSec
        run: mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs

      - name: Run OWASP Dependency-Check
        working-directory: InfoSec
        run: mvn org.owasp.plugins:dependency-check-maven:check

      - name: Upload Reports
        uses: actions/upload-artifact@v3.1.0
        with:
          name: reports
          path: |
            target/spotbugsXml.xml
            target/dependency-check-report.xml